# Generated by Django 3.0.8 on 2020-07-17 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20200715_1048'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='photo',
            field=models.ImageField(blank=True, default='', upload_to='users/photos', verbose_name='photo'),
        ),
    ]
